name: Publich

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup dotnet7
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 7.0.x
        
    - name: publish projects
      run: ./publish.bat

    - name: get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    
    - name: create release
      id: create_release
      uses: GongT/actions-recreate-release@v1
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        tag_name: v1.0.0.0
        release_name: v1.0.0.0.${{ steps.date.outputs.today }}
        draft: false
        prerelease: false
        
    - name: upload any
      id: upload-any
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash-any.zip
        asset_name: smash-any.zip
        asset_content_type: application/zip
    
    - name: upload win x64
      id: upload-win-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash-win-x64-single.zip
        asset_name: smash-win-x64-single.zip
        asset_content_type: application/zip

    - name: upload proxy any
      id: upload-proxy-any
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-any.zip
        asset_name: smash.proxy-any.zip
        asset_content_type: application/zip
    
    - name: upload proxy win x64
      id: upload-proxy-winx64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-win-x64-single.zip
        asset_name: smash.proxy-win-x64-single.zip
        asset_content_type: application/zip

    - name: upload proxy win arm64
      id: upload-proxy-win-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-win-arm64-single.zip
        asset_name: smash.proxy-win-arm64-single.zip
        asset_content_type: application/zip

    - name: upload proxy linux x64
      id: upload-proxy-linux-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-linux-x64-single.zip
        asset_name: smash.proxy-linux-x64-single.zip
        asset_content_type: application/zip

    - name: upload proxy linux arm64
      id: upload-proxy-linux-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-linux-arm64-single.zip
        asset_name: smash.proxy-linux-arm64-single.zip
        asset_content_type: application/zip

    - name: upload proxy osx x64
      id: upload-proxy-osx-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-osx-x64-single.zip
        asset_name: smash.proxy-osx-x64-single.zip
        asset_content_type: application/zip

    - name: upload proxy osx arm64
      id: upload-proxy-osx-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/smash.proxy-osx-arm64-single.zip
        asset_name: smash.proxy-osx-arm64-single.zip
        asset_content_type: application/zip
